In [1]:
import numpy as np
from numpy import random
import keras
from keras import backend as k
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.models import load_model
#print("hai")

Using TensorFlow backend.


In [3]:
from sklearn.metrics import confusion_matrix
from keras.models import load_model
import numpy as np

Using TensorFlow backend.


In [ ]:
'''def mplot(img):
    plt.gcf().clear()
    plt.imshow(img, cmap = 'gray', interpolation = 'bicubic')
    plt.xticks([]), plt.yticks([])  # to hide tick values on X and Y axis
    plt.show()
print(dataset[50])
mplot(dataset[50][0])
print(dataset[50][1].tolist().index(1)+1)
'''

In [5]:
model2=load_model('/home/jabir/Project/MHCR/modelMHCR_gray_2.8.96.97.h5')

In [6]:
def get_confusion_matrix_one_hot(model_results, truth):
        '''model_results and truth should be for one-hot format, i.e, have >= 2 columns,
        where truth is 0/1, and max along each row of model_results is model result
        '''
        assert model_results.shape == truth.shape
        num_outputs = truth.shape[1]
        confusion_matrix = np.zeros((num_outputs, num_outputs), dtype=np.int32)
        predictions = np.argmax(model_results,axis=1)
        assert len(predictions)==truth.shape[0]

        for actual_class in range(num_outputs):
            idx_examples_this_class = truth[:,actual_class]==1
            prediction_for_this_class = predictions[idx_examples_this_class]
            for predicted_class in range(num_outputs):
                count = np.sum(prediction_for_this_class==predicted_class)
                confusion_matrix[actual_class, predicted_class] = count
        assert np.sum(confusion_matrix)==len(truth)
        assert np.sum(confusion_matrix)==np.sum(truth)
        return confusion_matrix

In [7]:
predict=model2.predict(X_test)

NameError: name 'X_test' is not defined

In [17]:
con_mat=get_confusion_matrix_one_hot(predict,y_test)
print(con_mat)

[[351   2   0 ...   0   0   0]
 [  0 394   0 ...   0   0   0]
 [  0   0 427 ...   0   0   0]
 ...
 [  0   0   0 ... 417   0   0]
 [  0   0   0 ...   0 437   0]
 [  0   0   0 ...   0   0 388]]


In [18]:
def plot_confusion_matrix(cm,
                          target_names,
                          title='Confusion matrix',
                          cmap=None,
                          normalize=True):
    accuracy = np.trace(cm) / float(np.sum(cm))
    misclass = 1 - accuracy

    if cmap is None:
        cmap = plt.get_cmap('Blues')

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()

    if target_names is not None:
        tick_marks = np.arange(len(target_names))
        plt.xticks(tick_marks, target_names, rotation=45)
        plt.yticks(tick_marks, target_names)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]


    thresh = cm.max() / 1.5 if normalize else cm.max() / 2
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        if normalize:
            plt.text(j, i, "{:0.4f}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")
        else:
            plt.text(j, i, "{:,}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")


    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label\naccuracy={:0.4f}; misclass={:0.4f}'.format(accuracy, misclass))
    plt.show()

In [19]:
names=['ch'+str(i+1) for i in range(44)]

In [20]:
plot_confusion_matrix(cm           = con_mat, 
                      normalize    = False,
                      target_names = names,
                      title        = "Confusion Matrix")

In [ ]:
#model2.save('/home/workstation/Desktop/jab/MHCR/modelMHCR_gray_2.8.96.97.h5')

In [ ]:
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils.vis_utils import plot_model
#SVG(model_to_dot(model2).create(prog='dot', format='svg'))
plot_model(model2, to_file='/home/workstation/Desktop/jab/realtest/model_gray_2.8_96.97.png', show_shapes=True, show_layer_names=True)

In [ ]:

#del model2

In [ ]:
#np.save('/home/workstation/Desktop/jab/MHCR/X_norm.npy',X)